name: Build USB Virus Scanner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Show environment info
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Show installed packages
      run: |
        pip list

    - name: Install pyinstaller
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile usb_virus_scanner.py
        echo "Build completed"

    - name: List dist directory
      run: |
        ls -l dist/
        echo "Listing dist directory completed"

    - name: Check if executable exists
      run: |
        if [ -f dist/usb_virus_scanner.exe ]; then echo "Executable exists"; else echo "Executable does not exist"; fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: USB_Virus_Scanner
        path: dist/usb_virus_scanner.exe
